server:
  port: 8083

spring:
  application:
    name: ms-trazabilidad
  data:
    mongodb:
      uri: mongodb+srv://andresfelipeaya17_db_user:Ankelino17.@cluster0.jscsuat.mongodb.net/Trazabilidad?retryWrites=true&w=majority&appName=Cluster0

appDescription: "Pragma Ms-Trazabilidad"
appVersion: "1.0.0"